---
## DNS IP and gateway of the Management Network 
dns: "10.0.1.254"
gateway: 10.0.1.1


## Network Bond details
ifname1: bond1
ifname2: bond2
bondname1: Bond connection bond1
bondname2: Bond connection bond2

