- name: Create rhel subscription all nodes
  hosts: "{{ groups['add'] }}"
  gather_facts: false
  vars_files:
    - ../input.yaml
  roles:
    - role: /opt/hpe-solutions-openshift/DL-LTI-Openshift/external-ceph_deployment/playbooks/roles/subscriptions/

