    - name: Checking if the host is already registered?
      shell: subscription-manager status | grep -e "Current"|awk '{print $3}'
      register: issubscribed
      ignore_errors: yes

    - name: Registering hosts to Red Hat Subscription Manager
      redhat_subscription:
          state: present
          username: "{{ rhsub_username }}"
          password: "{{ rhsub_password }}"
          force_register: yes
          auto_attach: yes
      when:
          - issubscribed.stdout.find('Current') == -1
      ignore_errors: yes

    - name: Pulling the latest subscription data from RHSM
      command: subscription-manager refresh

    - name: Install KVM Virtualization  packages
      become: yes
      yum:
        name:
          - virt-manager
          - virt-install
          - virt-viewer
          - libvirt
          - cockpit-machines
          - cockpit
          - xauth
        state: latest

    - name: Enable firewalld service
      command: systemctl enable firewalld

    - name: Start firewalld service
      command: systemctl start firewalld

    - name: Status firewalld service
      command: systemctl status firewalld
      register: output

    - debug:
          var: output.stdout_lines

    - name: Enable libvirtd service
      command: systemctl enable libvirtd

    - name: Start libvirtd service
      command: systemctl start libvirtd

    - name: Status libvirtd service
      command: systemctl status libvirtd
      register: output1

    - debug:
        var: output1.stdout_lines

    - name: Enable cockpit service
      command: systemctl enable cockpit

    - name: Start cockpit service
      command: systemctl start cockpit

    - name: Status cockpit service
      command: systemctl status cockpit
      register: output2
    - name: Copy environment file to worker nodes
      copy:
        src: /etc/environment
        dest: /etc/environment
        owner: root
        group: root

    - name: Replace domain in resolv.conf file
      lineinfile:
        path: /etc/resolv.conf
        regexp: "search*"
        line: 'search {{ common.base_domain }}'

    - name: Delete existing nameserver
      lineinfile:
        path: /etc/resolv.conf
        regexp: "nameserver*"
        state: absent

    - name: Add nameserver in resolv.conf file
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver {{ master_binddns }} \nnameserver {{ slave1_binddns }} \nnameserver {{ slave2_binddns }}"


    - name: Replace domain in network scripts file
      lineinfile:
        path: /etc/sysconfig/network-scripts/{{ common.ifcfg_filename }}
        regexp: "DOMAIN*"
        line: 'DOMAIN={{ common.base_domain }}'

    - name: Add master DNS in network scripts file
      lineinfile:
        path: /etc/sysconfig/network-scripts/{{ common.ifcfg_filename }}
        regexp: "DNS1*"
        line: 'DNS1={{ master_binddns }}'

    - name: Add slave DNS in network scripts file
      lineinfile:
        path: /etc/sysconfig/network-scripts/{{ common.ifcfg_filename }}
        insertafter: "^DNS1={{ master_binddns }}"
        line: "DNS2={{ slave1_binddns }} \nDNS3={{ slave2_binddns }}"
        state: present

    -  name: Restart the service
       service:
            name: NetworkManager
            state: restarted
            enabled: true

    - name: Make /etc/resolv.conf immutable
      command: chattr -i /etc/resolv.conf

    - debug:
          var: output2.stdout_lines

    - name: Validate host virtualization
      command: virt-host-validate
      register: output3

    - debug:
           var: output3.stdout_lines


