###
## Copyright (2021) Hewlett Packard Enterprise Development LP
##
## Licensed under the Apache License, Version 2.0 (the "License");
## You may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
####

---
- name: prepare hosts
  hosts: rhel_nodes 
  gather_facts: true
  become: true
  vars_files:
    - input.yaml

  tasks:
    - name: Checking if the host is already registered?
      shell: subscription-manager status | grep -e "Current"|awk '{print $3}'
      register: issubscribed
      ignore_errors: yes

    - name: Registering hosts to Red Hat Subscription Manager
      redhat_subscription:
          state: present
          username: "{{ rhsub_username }}"
          password: "{{ rhsub_password }}"
          force_register: yes
          auto_attach: yes
      when:
          - issubscribed.stdout.find('Current') == -1
      ignore_errors: yes

    - name: Pulling the latest subscription data from RHSM
      command: subscription-manager refresh

    - name: Attaching the pool ID for Openshift Container Platform
      redhat_subscription:
          state: present
          username: "{{ rhsub_username }}"
          password: "{{ rhsub_password }}"
          pool: 'Red Hat Advanced Cluster Management for Kubernetes and OpenShift Container Platform'

    - name: Enabling Reqired repositories for ocp 4.6
      rhsm_repository:
        name: [rhel-7-server-rpms , rhel-7-server-extras-rpms , rhel-7-server-optional-rpms , rhel-7-server-ansible-2.9-rpms , rhel-7-fast-datapath-rpms , rhel-7-server-ose-4.6-rpms]
      when: ocp_version == 4.6

    - name: Enabling Reqired repositories for ocp 4.7
      rhsm_repository:
        name: [rhel-7-server-rpms , rhel-7-server-extras-rpms , rhel-7-server-optional-rpms, rhel-7-server-ansible-2.9-rpms , rhel-7-fast-datapath-rpms , rhel-7-server-ose-4.7-rpms]
      when: ocp_version == 4.7


    - name: Disabling firewall
      service:
        name: firewalld
        state: stopped
        enabled: false

  

   

    
