---
#- name: Install virt_pool module dependencies
  #pacman: name={{ item }} state=present
  #with_items:
    #- python2-lxml
    #- libvirt-pythoni

- name: Create PV for storage pool
  command: pvcreate /dev/sdb

- name: Create volume group for storage pool
  command: vgcreate {{virt_dir_storage_pool_vg}} /dev/sdb

- name: Create logical volume for storage pool
  lvol: vg={{virt_dir_storage_pool_vg}} lv={{virt_dir_storage_pool_lv}} size={{virt_dir_storage_pool_size}}

- name: Create fs on storage pool volume
  filesystem: fstype=ext4 dev=/dev/{{virt_dir_storage_pool_vg}}/{{virt_dir_storage_pool_lv}}
  
- name: Create mountpoint for storage pool
  mount:
    name: /mnt/{{virt_dir_storage_pool_vg}}_{{virt_dir_storage_pool_lv}}
    fstype: ext4
    src: /dev/{{virt_dir_storage_pool_vg}}/{{virt_dir_storage_pool_lv}}
    state: mounted
    passno: 2

- name: Create directoy storage pool
  virt_pool:
    name: "{{ virt_dir_storage_pool_vg }}_{{ virt_dir_storage_pool_lv}}"
    command: define
    xml: "{{ lookup('template', 'dir_pool.j2') }}"

- name: Activate storage pool
  virt_pool:
    name: "{{ virt_dir_storage_pool_vg }}_{{ virt_dir_storage_pool_lv}}"
    state: active
    autostart: yes

- name: Activate autostart
  virt_pool:
    name: "{{ virt_dir_storage_pool_vg }}_{{ virt_dir_storage_pool_lv}}"
    autostart: yes


