- name: prepare hosts
  become: true
  yum:
   name:
     - bind
     - bind-utils
   state: latest

- name: Enable named service
  command: systemctl enable named

- name: Start named service
  command: systemctl start named

- name: Status named service
  command: systemctl status named
  register: output

- debug:
    var: output.stdout_lines

