---
- name: Deploy Haproxy LoadBalancer
  hosts: lb
  gather_facts: True
  connection: ssh
  become: true
  ignore_errors: False
  
  tasks:
  - name: Installing Haproxy loadBalancer
    block:
    
      - name: Stop and disable firewall service.
        service:
          name: firewalld
          state: stopped
          enabled: False

      - name: disable selinux
        selinux:
          state: disabled

      - name: Install Haproxy package
        yum:
          name: haproxy
          state: present

      - name: Stop Haproxy service if running already
        service:
          name: haproxy
          state: stopped

      - name: Dynamically copying HAproxy Configuration file
        template:
          src: haproxy.cfg.j2
          dest: /etc/haproxy/haproxy.cfg
          owner: root
          group: root
          mode: 0644
        notify:
        - Restart HAProxy Service
        
      - name: Allow HTTPS to the firewall
        firewalld:
          service: https
          permanent: true
          state: enabled

      - name: Add TCP ports to the firewall
        firewalld:
          port: "{{ item }}"
          permanent: yes
          state: enabled
        with_items:
          - 6443/tcp
          - 22623/tcp
          - 80/tcp
          - 443/tcp

      - name: Restart firewall service
        systemd:
          name: firewalld
          state: reloaded
          
    when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7"
    
  handlers:
  - name: Restart HAProxy Service
    service:
      name: haproxy
      state: started
      enabled: true
