---
- name: Replace domain in resolv.conf file
  lineinfile:
    path: /etc/resolv.conf
    regexp: "search*"
    line: 'search {{ common.base_domain }}'

- name: Delete existing nameserver
  lineinfile:
    path: /etc/resolv.conf
    regexp: "nameserver*"
    state: absent

- name: Add nameserver in resolv.conf file
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver {{ master_binddns }}"


- name: Replace domain in network scripts file
  lineinfile:
    path: /etc/sysconfig/network-scripts/{{ common.ifcfg_filename }}
    regexp: "DOMAIN*"
    line: 'DOMAIN={{ common.base_domain }}'

- name: Add master DNS in network scripts file
  lineinfile:
    path: /etc/sysconfig/network-scripts/{{ common.ifcfg_filename }}
    regexp: "DNS1*"
    line: 'DNS1={{ master_binddns }}'

-  name: Restart the service
   service:
         name: NetworkManager
         state: restarted
         enabled: true

        
