---
- name: Prepare vCenter by creating the datacenter, cluster and adding hosts into the cluster
  hosts:
    - localhost
  gather_facts: true
  vars_files:
   - ../roles/prepare_vcenter/tasks/vsphere_hosts.yml
   - ../secret.yml
  roles:
   - ../roles/prepare_vcenter
