---
  - name: Check the /etc/hosts entries
    lineinfile:
      path: /etc/hosts
      line: "{{ mirror_registry_ip }} {{ mirror_registry_fqdn }}"  
      state: present
        
  - name: Install Mirror Registry
    shell: |
      mkdir -p {{ base_path }}/airgap/mirror_registry/quay-install
      mirror-registry install --quayHostname {{ mirror_registry_fqdn }} --quayRoot {{ base_path }}/quay-install
    register: mirror_registry

  - name: Extract the Credentilas using regex_search
    set_fact:
      creds: "{{ mirror_registry.stdout | regex_search('credentials \\(.*?, ([a-zA-Z0-9]+)\\)', '\\1') }}"

  - name: show extracted password
    debug:
      msg: "Extracted Password is: {{ creds }}"
    
  - name: Check if credentials file exists
    stat:
      path: "{{ base_path }}/airgap/mirror_registry/credentials"
    register: file_status

  - name: Delete the credentials file if already exists
    file:
      path: "{{ base_path }}/airgap/mirror_registry/credentials"
      state: absent
    when: file_status.stat.exists

  - name: store the credentials to a file
    shell: |
      touch "{{ base_path }}/airgap/mirror_registry/credentials"
      echo -n "{{ creds }}" | tail -c +3 | head -c -2 > {{ base_path }}/airgap/mirror_registry/credentials
