---

- hosts:
    - masters
    - infra
    - apps
  tasks:  
   - name: "pull docker images"
     command: "docker pull {{item}}"
     with_items:
        - "openshift3/ose-deployer:v3.10"
        - "openshift3/ose-docker-registry:v3.10"
        - "openshift3/ose-haproxy-router:v3.10"
        - "registry.access.redhat.com/openshift3/registry-console:v3.10"
        - "openshift3/ose-pod:v3.10"
 
