---
  - name: Download OpenShift CLI
    shell: |
      cd /usr/local/bin
      wget --execute="robots = off" --mirror --convert-links --no-parent --wait=5 https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.16.10/ -A "openshift-*-linux-4.16.10*" --no-directories --no-check-certificate

  - name: Extract the OpenShift CLI tar file
    shell: |
      cd /usr/local/bin
      cat *.tar.gz | tar zxvf - -i
