---

    - name: Install HTTPD package
      package:
        name: httpd
        state: present
    - name: Start HTTPD service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Creates directory
      ansible.builtin.file:
        path: /var/www/html/rhel9
        state: directory
        owner: root
        group: root
        mode: 0775

    - name: insert lineinfile in /etc/fstab file
      lineinfile:  
        dest: /etc/fstab
        line: /root/rhel-9.4-x86_64-dvd.iso               /var/www/html/rhel9/     iso9660   loop  0 0
        state: present  
        create: yes            

    - name: Ensure all fstab entries are mounted
      command: mount -a

     - name: Dynamically coping local repo file
       template:
         src: ./rhel9_local.repo.j2
         dest: /etc/yum.repos.d/rhel9_local.repo
         owner: root
         group: root
         mode: 0644

     - name: Check the YUM repo list
       command: yum repolist       
       register: yum_repolist

     - debug:
         msg: "{{ yum_repolist.stdout }}"

     - debug: 
         msg: "{{ yum_repolist.stderr }}"

     - name: Check redhat.repo file exists or not
       stat: path=/etc/yum.repos.d/redhat.repo
       register: redhat_repo

     - name: Move redhat.repo file to /tmp folder
       command: mv /etc/yum.repos.d/redhat.repo /tmp/
       when: redhat_repo.stat.exists

     - name: Permit TCP ports and services in firewall rule
       shell: |
             firewall-cmd --add-service={http,https} --permanent
             firewall-cmd --reload         

     - name: Enables the repositories defined outside redhat.repo    
       lineinfile:
         path: /etc/yum/pluginconf.d/subscription-manager.conf
         regexp: '^disable_system_repos='
         line: 'disable_system_repos=0'
         state: present

     - name: suppress or prevent warning message
       lineinfile:
         path: /etc/yum/pluginconf.d/subscription-manager.conf
         regexp: '^enabled='
         line: 'enabled=0'
         state: present           
