- name: Log in to oVirt 
      ovirt_auth:
         url: "{{ vault_engine_url }}"
         username: "{{ vault_engine_user }}"
         password: "{{ vault_engine_password }}"
         ca_file: "{{ engine_cafile }}"
- name: Erase Master vms
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        state: absent
        name: "{{ item.key }}"
      with_dict: "{{ vms_3nics }}"

- name: Erase LB vms
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        state: absent
        name: "{{ item.key }}"
      with_dict: "{{ vms_2nics }}"
 

- name: Erase etcd vms
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        state: absent
        name: "{{ item.key }}"
      with_dict: "{{ vms }}"


- name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always
