###
## Copyright (2019) Hewlett Packard Enterprise Development LP
##
## Licensed under the Apache License, Version 2.0 (the "License");
## You may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
####

---
- name: Copy the file from ansible engine to 3PAr Volume on master01
  copy: src=/mnt/ dest=/StoreOnce_vol/
  when: 'inventory_hostname in groups["storeonce_vol_node"]|default([])'

- block:
  - name: Fetch Checksum from ansible engine as destination of file
    stat:
      path: "/mnt/{{ inventory_hostname }}.tar.bz2"
      checksum_algorithm: sha256
    delegate_to: localhost
    register: local_files

  - name: Fetch Checksum from remote host as source of file
    stat:
      path: "/StoreOnce_vol/{{ inventory_hostname }}.tar.bz2"
      checksum_algorithm: sha256
    register: remote_files
    delegate_to: "{{ groups.storeonce_vol_node[0] }}"
 
  - block:
    - name: End play if source and destination checksum does not match
      debug:
        msg: "Ending the play. Reason: source and destination checksum does not match. {{ remote_files.stat.checksum }} and {{ local_files.stat.checksum}}"

    - meta: end_play
    when: remote_files.stat.checksum != local_files.stat.checksum


  

 

