---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: registry
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: hpe.com/nimble
parameters:
  description: "Volume provisioned by HPE Nimble Storage Kube Storage Controller from Registry StorageClass"
  fsMode: "0770"

