###
## Copyright (2018) Hewlett Packard Enterprise Development LP
##
## Licensed under the Apache License, Version 2.0 (the "License");
## You may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
####


---
# vars file for deploy-vm
engine_cafile: '/etc/pki/ovirt-engine/ca.pem'
datacenter: Default
cluster: Default
network: 'ovirtmgmt'
vmtemplate: rhel7-template_7.5_2d-50G
mgmt_gateway: 10.0.1.1
mgmt_mask: 255.255.0.0
mgmt_dns: 10.0.1.254
#private_hosted_zone: tennet.local

public_hosted_zone: tennet.local
#pub_mask: 255.0.0.0
#pub_gateway: 20.1.1.1
#pub_dns: 20.1.1.254

fqdnmaster1: nmaster01.tennet.local
fqdnmaster2: nmaster02.tennet.local
fqdnmaster3: nmaster03.tennet.local
fqdnetcd1: netcd01.tennet.local
fqdnetcd2: netcd02.tennet.local
fqdnetcd3: netcd03.tennet.local
fqdninfra1: ninfra01.tennet.local
fqdninfra2: ninfra02.tennet.local
fqdninfra3: ninfra03.tennet.local
fqdnlb1: nlb01.tennet.local
fqdnlb2: nlb02.tennet.local

#fqdn of RHVH cluster where the VMs are getting deployed
fqdnrhv1: nrhvh01.tennet.local
fqdnrhv2: nrhvh02.tennet.local
fqdnrhv3: nrhvh03.tennet.local

storage_mask: 255.255.0.0

nmaster01_ip: 10.0.140.10
nmaster01_ip2: 30.0.10.7
nmaster01_ip3: 40.0.10.7

nmaster02_ip: 10.0.140.11
nmaster02_ip2: 30.0.10.7
nmaster02_ip3: 40.0.10.7

nmaster03_ip: 10.0.140.12
nmaster03_ip2: 30.0.10.7
nmaster03_ip3: 40.0.10.7

nlb01_ip: 10.0.170.10
#nlb01_ip2: 20.0.10.40

nlb02_ip: 10.0.170.11
#nlb02_ip2: 20.0.10.41

ninfra01_ip: 10.0.160.10
ninfra01_ip2: 30.0.10.30
ninfra01_ip3: 40.0.10.30

ninfra02_ip: 10.0.160.11
ninfra02_ip2: 30.0.10.31
ninfra02_ip3: 40.0.10.31

ninfra03_ip: 10.0.160.12
ninfra03_ip2: 30.0.10.32
ninfra03_ip3: 40.0.10.32

netcd01_ip : 10.0.150.10
netcd02_ip : 10.0.150.11
netcd03_ip : 10.0.150.12

vms:
  netcd01.tennet.local:
    ip: "{{netcd01_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
    domainsearch: "{{public_hosted_zone}}"
#    domainsearch: "{{private_hosted_zone}}"
    cpu: 4
    mem: 16GiB

  netcd02.tennet.local:
    ip: "{{netcd02_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
    domainsearch: "{{public_hosted_zone}}"
#    domainsearch: "{{private_hosted_zone}}"
    cpu: 4
    mem: 16GiB

  netcd03.tennet.local:
    ip: "{{netcd03_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
    domainsearch: "{{public_hosted_zone}}"
#    domainsearch: "{{private_hosted_zone}}"
    cpu: 4
    mem: 16GiB

#vms_2nics:

  nlb01.tennet.local:
    ip: "{{nlb01_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
    domainsearch: "{{public_hosted_zone}}"
#    domainsearch: "{{private_hosted_zone}}"
#    ip2: "{{nlb01_ip2}}"
#    mask2: "{{pub_mask}}"
#    gateway2: "{{pub_gateway}}"
#    nameserver2: "{{pub_dns}}"
#    domainsearch2: "{{public_hosted_zone}}"
    cpu: 2
    mem: 8GiB

  nlb02.tennet.local:
    ip: "{{nlb02_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
    domainsearch: "{{public_hosted_zone}}"
#    domainsearch: "{{private_hosted_zone}}"
#    ip2: "{{nlb02_ip2}}"
#    mask2: "{{pub_mask}}"
#    gateway2: "{{pub_gateway}}"
#    nameserver2: "{{pub_dns}}"
#    domainsearch2: "{{public_hosted_zone}}"
    cpu: 2
    mem: 8GiB

vms_3nics:

  ninfra01.tennet.local:
    ip: "{{ninfra01_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
#    domainsearch: "{{private_hosted_zone}}"
    domainsearch: "{{public_hosted_zone}}"
    cpu: 4
    mem: 16GiB
    ip2: "{{ninfra01_ip2}}"
    mask2: "{{storage_mask}}"
    ip3: "{{ninfra01_ip3}}"
    mask3: "{{storage_mask}}"    

  ninfra02.tennet.local:
    ip: "{{ninfra02_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
#    domainsearch: "{{private_hosted_zone}}"
    domainsearch: "{{public_hosted_zone}}"
    cpu: 4
    mem: 16GiB
    ip2: "{{ninfra02_ip2}}"
    mask2: "{{storage_mask}}"
    ip3: "{{ninfra02_ip3}}"
    mask3: "{{storage_mask}}"

  ninfra03.tennet.local:
    ip: "{{ninfra03_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
#    domainsearch: "{{private_hosted_zone}}"
    domainsearch: "{{public_hosted_zone}}"
    cpu: 4
    mem: 16GiB
    ip2: "{{ninfra03_ip2}}"
    mask2: "{{storage_mask}}"
    ip3: "{{ninfra03_ip3}}"
    mask3: "{{storage_mask}}"

  nmaster01.tennet.local:
    ip: "{{nmaster01_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
#    domainsearch: "{{private_hosted_zone}}"
    domainsearch: "{{public_hosted_zone}}"
    cpu: 4
    mem: 16GiB
    ip2: "{{nmaster01_ip2}}"
    mask2: "{{storage_mask}}"
    ip3: "{{nmaster01_ip3}}"
    mask3: "{{storage_mask}}"

  nmaster02.tennet.local:
    ip: "{{nmaster02_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
#    domainsearch: "{{private_hosted_zone}}"
    domainsearch: "{{public_hosted_zone}}"
    cpu: 4
    mem: 16GiB
    ip2: "{{nmaster02_ip2}}"
    mask2: "{{storage_mask}}"
    ip3: "{{nmaster02_ip3}}"
    mask3: "{{storage_mask}}"

  nmaster03.tennet.local:
    ip: "{{nmaster03_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
#    domainsearch: "{{private_hosted_zone}}"
    domainsearch: "{{public_hosted_zone}}"
    cpu: 4
    mem: 16GiB
    ip2: "{{nmaster03_ip2}}"
    mask2: "{{storage_mask}}"
    ip3: "{{nmaster03_ip3}}"
    mask3: "{{storage_mask}}"


