---
  - name: Read password from file
    set_fact:
      password: "{{ lookup('file', password_file_path) }}"

  - name: Encode the password in base64
    shell: echo -n 'init:{{ password }}' | base64 -w0
    register: encoded_password

  - name: Display the base64-encoded password
    debug:
      msg: "Encoded password: {{ encoded_password.stdout }}"      

  - name: Use the base64-encoded password (as an example)
    shell: |
      echo "Using encoded password: {{ encoded_password.stdout }}"      

  - name: Read the current JSON file
    slurp:
      path: "{{ base_path }}/json_pull_secret.json"
    register: json_file

  - name: Parse the JSON content
    set_fact:
      json_content: "{{ json_file.content | b64decode | from_json }}"

  - name: Add registry information to JSON content
    set_fact:
      json_content_updated: "{{ json_content | combine({'auths': {mirror_registry_fqdn: {'auth': encoded_password.stdout, 'email': email}}}, recursive=True) }}"

  - name: Write updated content back to JSON file
    copy:
      content: "{{ json_content_updated | to_nice_json }}"
      dest: "{{ base_path }}/json_pull_secret.json"
