---
    
- name: Dynamically copying HAproxy Configuration file
  template:
    src: ./haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644

- name: Restart HAProxy Service
  service:
    name: haproxy
    state: started
    enabled: true

- name: Restart Keepalived Service
  service:
    name: keepalived
    state: started
    enabled: true
        

- name: Reload firewall service
  systemd:
    name: firewalld
    state: reloaded
   
