---
  - name: Delete existing dist folder
    file:
      path: "{{ base_path }}/playbooks/roles/generate_ignition_files/ignitions"
      state: absent

  - name: Create Ignition directory
    file:
      path: "{{ base_path }}/playbooks/roles/generate_ignition_files/ignitions"
      state: directory

  - name: Encode the password in base64
    shell: echo -n 'init:{{ lookup("file", "{{ base_path }}/credentials") }}' | base64 -w0
    register: encoded_password
 
  - name: Read the content of ssl.cert
    slurp:
      src: "{{ base_path }}/quay-install/quay-config/ssl.cert"
    register: ssl_cert_content

  - name: Set additionalTrustBundle variable
    set_fact:
      additionalTrustBundle: "{{ ssl_cert_content['content'] | b64decode }}"

  - name: install-config file
    ansible.builtin.template:
      src: install-config-template-airgap.j2
      dest: "{{ base_path }}/playbooks/roles/generate_ignition_files/ignitions/install-config.yaml"

  - name: take the back up of install-config file
    copy:
      src: "{{ base_path }}/playbooks/roles/generate_ignition_files/ignitions/install-config.yaml"
      dest: "{{ base_path }}/playbooks/roles/generate_ignition_files/install-config.yaml"

  - name: create manifests files
    command: "openshift-install create manifests --dir={{ base_path }}/playbooks/roles/generate_ignition_files/ignitions"

  - name: create ignition files
    command: "openshift-install create ignition-configs  --dir={{ base_path }}/playbooks/roles/generate_ignition_files/ignitions"

