---
- name: Convert pull secret to JSON format
  hosts: localhost
  become: yes
  gather_facts: False
  vars_files:
    - ../../../input.yaml
  roles:
    - role: roles/create_json_pull_secret

