---
- name: Generate SSL Certificates
  hosts: localhost
  become: yes
  gather_facts: False
#  vars_prompt:
#    - name: country_name
#      prompt: "Enter Country Name (2 letter code)"
#      private: no
#    - name: state_or_province
#      prompt: "Enter State or Province Name"
#      private: no
#    - name: locality_name
#      prompt: "Enter Locality Name (e.g., city)"
#      private: no
#    - name: organization_name
#      prompt: "Enter Organization Name"
#      private: no
#    - name: organizational_unit
#      prompt: "Enter Organizational Unit Name"
#      private: no
#    - name: email_address
#      prompt: "Enter Email Address"
#      private: no
#    - name: challenge_password
#      prompt: "Enter Challenge Password (optional)"
#      private: no
#    - name: optional_company_name
#      prompt: "Enter Optional Company Name (optional)"
#      private: no        
  vars_files:
    - ../../../input.yaml
  roles:
    - role: roles/generate_ssl_certs

