---
- name: Update json pull secret with Mirror registry login details
  hosts: localhost
  become: yes
  gather_facts: False
  vars_files:
    - ../../../input.yaml
  roles:
    - role: roles/update_json_pull_secret
