---
- block:
    - name: Is the host already registered?
      command: "subscription-manager list"
      register: subscribed
      ignore_errors: yes

    - name: Unregister host
      redhat_subscription:
        state: absent
      when: "'Subscribed' in subscribed.stdout"
      ignore_errors: yes

