###
## Copyright (2018) Hewlett Packard Enterprise Development LP
##
## Licensed under the Apache License, Version 2.0 (the "License");
## You may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
####



---
  
- name: Install Basic Utils
  yum:
     name: "{{item}}"
     state: latest
  with_items:
  - wget
  - git
  - net-tools
  - bind-utils
  - yum-utils
  - iptables-services
  - bridge-utils
  - bash-completion
  - kexec-tools
  - sos
  - psacct

- name: Perform an Update
  yum:
     name: '*'
     state: latest

#- name: reboot host
#  shell: /sbin/shutdown -r now
#  become: true

#- name: waiting for server booting up
#  local_action: wait_for
#  args:
#    host: ''
#    port: 22
#    delay: 30
#    timeout: 300
#    state: started
#  become: false

