apiVersion: v1
baseDomain:  
compute:
- hyperthreading: Enabled   
  name: worker
  replicas: 2
controlPlane:
  hyperthreading: Enabled   
  name: master 
  replicas: 3 
metadata:
  name:  
networking:
  clusterNetworks:
  - cidr: 12.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {} 
pullSecret: ''
sshKey: ''
