---
  - name: Copy OCP tools
    block:
      - name: Copying openshift components
        become: true
        copy:
          src: "{{ base_path }}/"
          dest: "{{ base_path }}/"
          owner: root
          group: root
          mode: 775

      - name: Copy oc to path
        become: true
        copy:
          src: "{{ base_path }}/playbooks/roles/download_ocp_packages/library/openshift_components/oc"
          dest: /usr/local/bin/
          owner: root
          group: root
          mode: 775

      - name: Copy openshift-install to path
        become: true
        copy:
          src: "{{ base_path }}/playbooks/roles/download_ocp_packages/library/openshift_components/openshift-install"
          dest: /usr/local/bin/
          owner: root
          group: root
          mode: 775

      - name: Copy boot images to Rhel7 installer
        become: true
        copy:
          src: "/tmp/image/"
          dest: /tmp/image/
          owner: root
          group: root
          mode: 775
        delegate_to: "{{ rhel7_installer_IP }}"


