---
- name: Create manifests and ignition files
  hosts: rhel9_installerVM
  become: yes
  gather_facts: true
  vars_files:
    - ../input.yaml
  roles:
    - role: roles/generate_ignition_files


