---
- name: Prepare rhel 9.4 Installer VM to add worker nodes
  hosts: rhel9_installerVM
  gather_facts: True
  vars_files:
    - ../input.yaml
  roles:
    - role: roles/prepare_installer_vm

