---
- name: Create rhel 9.4 Installer VM to add worker nodes
  hosts: "{{ groups['kvm_nodes'][0] }}"
  gather_facts: True
  vars_files:
    - ../input.yaml
  roles:
    - role: roles/rhel9_installerVM
   

