---
- name: Dynamically copying Named Configuration file
  template:
    src: ./named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: root
    mode: 0644

- name: Dynamically copying Forward Zone file
  template:
    src: ./forward.isv.j2
    dest: /var/named/forward.isv
    owner: root
    group: root
    mode: 0644

- name: Dynamically copying Reverse Zone file
  template:
    src: ./reverse.isv.j2
    dest: /var/named/reverse.isv
    owner: root
    group: root
    mode: 0644

- name: Provide the required permisions to the zone files
  shell: |       # Multiple commands in Ansible shell module
       chown named:named -R /var/named ; restorecon -rv /var/named
       chcon system_u:object_r:named_zone_t:s0 /var/named/forward.isv
       chcon system_u:object_r:named_zone_t:s0 /var/named/reverse.isv
  become: true
  args:
    chdir: /var/named
  notify:
  - Restart Named Service

- name: Permit (TCP & UDP port 53) in firewall rule
  shell: |
       firewall-cmd  --permanent --add-port=53/tcp
       firewall-cmd  --permanent --add-port=53/udp
       firewall-cmd --reload
  become: true

