---
    - name: Checking if the host is already registered?
      shell: subscription-manager status | grep -e "Current"|awk '{print $3}'
      register: issubscribed
      ignore_errors: yes

    - name: Registering hosts to Red Hat Subscription Manager
      redhat_subscription:
          state: present
          username: "{{ rhsub_username }}"
          password: "{{ rhsub_password }}"
          pool_ids: "{{ pool_id }}"
          force_register: yes
      when:
          - issubscribed.stdout.find('Current') == -1
      ignore_errors: yes

    - name: Disable all the enabled RHSM repositories
      shell: subscription-manager repos --disable="*"

    - name: Enable the repositories required by OpenShift Container Platform 4.10
      shell: subscription-manager repos --enable="rhel-8-for-x86_64-baseos-rpms" --enable="rhel-8-for-x86_64-appstream-rpms" --enable="rhocp-4.10-for-rhel-8-x86_64-rpms" --enable="fast-datapath-for-rhel-8-x86_64-rpms"

    - name: Stop and disable firewall service.
      service:
        name: firewalld
        state: stopped
        enabled: False
  
    - name: Copy environment file to worker nodes
      copy:
        src: /etc/environment
        dest: /etc/environment
        owner: root
        group: root




