---
  - name: copy ISO image to head node
    become: true
    copy:
      src: /usr/share/nginx/html/{{ config.OS_image_name }}
      dest: /tmp/
      owner: root
      group: root
      mode: 0644

  - name: copy ks.cfg file to head node
    become: true
    template:
      src: ks.conf.j2
      dest: /tmp/ks.cfg
      owner: root
      group: root
      mode: 777

  - name: create installer VM on KVM node1
    shell:
      cmd: >-
          virt-install
          --name rhel9_installer
          --memory=16000
          --vcpus=4
          --os-type linux
          --location /tmp/{{ config.OS_image_name }}
          --disk path=/mnt/ocp_vms/installer.qcow2,device=disk,size=250,bus=virtio
          --network bridge={{ common.interface_name }}
          --os-variant=rhel9.0
          --autostart
          --console pty,target_type=virtio
          --initrd-inject /tmp/ks.cfg
          --extra-args "inst.ks=file:/ks.cfg console=tty0 console=ttyS0,115200n8"
          --wait 12

  - name: ping the VM to check it's reachable
    wait_for:
      port: 22
      host: "{{ rhel9_installer_IP }}"
      search_regex: OpenSSH
      delay: 10

