---
- name: Ensure rsync is installed
  become: true
  ansible.builtin.package:
    name: rsync
    state: present

- name: Copy the installation directory to manager1
  become: true
  shell: rsync -a /opt/ root@{{ servers[0].Host_IP }}:/opt/


