    - name: Checking if the host is already registered?
      shell: subscription-manager status | grep -e "Current"|awk '{print $3}'
      register: issubscribed
      ignore_errors: yes
      when: is_environment_airgap == 'no'

    - name: Registering hosts to Red Hat Subscription Manager
      redhat_subscription:
          state: present
          username: "{{ rhsub_username }}"
          password: "{{ rhsub_password }}"
          force_register: yes
          auto_attach: yes
      when:
          - when: is_environment_airgap == 'no'
          - issubscribed.stdout.find('Current') == -1
      ignore_errors: yes


    - name: Dynamically coping local repo file
      template:
        src: ./client.repo.j2
        dest: /etc/yum.repos.d/client.repo
        owner: root
        group: root
        mode: 0644
      when: is_environment_airgap == 'yes'

    - name: Check the YUM repo list
      command: yum repolist
      register: yum_repolist
      when: is_environment_airgap == 'yes'

    - debug:
        msg: "{{ yum_repolist.stdout }}"
      when: is_environment_airgap == 'yes'

    - debug:
        msg: "{{ yum_repolist.stderr }}"
      when: is_environment_airgap == 'yes'

    - name: Check redhat.repo file exists or not
      stat: path=/etc/yum.repos.d/redhat.repo
      register: redhat_repo
      when: is_environment_airgap == 'yes'

    - name: Move redhat.repo file to /tmp folder
      command: mv /etc/yum.repos.d/redhat.repo /tmp/
      when: 
        - is_environment_airgap == 'yes'
        - redhat_repo.stat.exists

    - name: Permit TCP ports and services in firewall rule
      shell: |
            firewall-cmd --add-service={http,https} --permanent
            firewall-cmd --reload
      when: is_environment_airgap == 'yes'

    - name: Enables the repositories defined outside redhat.repo
      lineinfile:
        path: /etc/yum/pluginconf.d/subscription-manager.conf
        regexp: '^disable_system_repos='
        line: 'disable_system_repos=0'
        state: present
      when: is_environment_airgap == 'yes'

    - name: suppress or prevent warning message
      lineinfile:
        path: /etc/yum/pluginconf.d/subscription-manager.conf
        regexp: '^enabled='
        line: 'enabled=0'
        state: present
      when: is_environment_airgap == 'yes'
        

    - name: Install required ansible packages
      command: ansible-galaxy collection install ansible.posix
      delegate_to: localhost

    - name: Pulling the latest subscription data from RHSM
      command: subscription-manager refresh
      when: is_environment_airgap == 'no'

    - name: Install KVM Virtualization  packages
      become: yes
      yum:
        name:
          - virt-manager
          - virt-install
          - virt-viewer
          - libvirt
          - cockpit-machines
        state: latest

    - name: Enable libvirtd service
      command: systemctl enable libvirtd

    - name: Start libvirtd service
      command: systemctl start libvirtd

    - name: Enable cockpit service
      command: systemctl enable cockpit

    - name: Start cockpit service
      command: systemctl start cockpit

    - name: Status cockpit service
      command: systemctl status cockpit
      register: output

    - debug:
          var: output.stdout_lines

    - name: Status libvirtd service
      command: systemctl status libvirtd
      register: output1

    - debug:
           var: output1.stdout_lines


    - name: Validate host virtualization
      command: virt-host-validate
      register: output2

    - debug:
           var: output2.stdout_lines


