###
## Copyright (2018) Hewlett Packard Enterprise Development LP
##
## Licensed under the Apache License, Version 2.0 (the "License");
## You may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
#### 

engine_url: https://rhvm.tennet.com/ovirt-engine/api
engine_cafile: '/etc/pki/ovirt-engine/ca.pem'
datacenter: Default
cluster: Default
network: 'ovirtmgmt/ovirtmgmt'
vmtemplate: rhel7-template_7.5_3par-2d-50G

vms_1nics:
  oshift-fc-etcd1.tennet.local:
    ip: 10.0.0.137
    mask: 255.255.0.0
    gateway: 10.0.1.1
    nameserver: 10.0.1.254 20.1.1.254
    domainsearch: tennet.local
    cpu: 4
    mem: 16GiB
  oshift-fc-etcd2.tennet.local:
    ip: 10.0.0.138
    mask: 255.255.0.0
    gateway: 10.0.1.1
    nameserver: 10.0.1.254 20.1.1.254
    domainsearch: tennet.local
    cpu: 4
    mem: 16GiB
  oshift-fc-etcd3.tennet.local:
    ip: 10.0.0.139
    mask: 255.255.0.0
    gateway: 10.0.1.1
    nameserver: 10.0.1.254 20.1.1.254
    domainsearch: tennet.local
    cpu: 4
    mem: 16GiB
  oshift-fc-m1.tennet.local:
    ip: 10.0.0.134
    mask: 255.255.0.0
    gateway: 10.0.1.1
    nameserver: 10.0.1.254 20.1.1.254
    domainsearch: tennet.local
    cpu: 4
    mem: 16GiB
  oshift-fc-m2.tennet.local:
    ip: 10.0.0.135
    mask: 255.255.0.0
    gateway: 10.0.1.1
    nameserver: 10.0.1.254 20.1.1.254
    domainsearch: tennet.local
    cpu: 4
    mem: 16GiB
  oshift-fc-m3.tennet.local:
    ip: 10.0.0.136
    mask: 255.255.0.0
    gateway: 10.0.1.1
    nameserver: 10.0.1.254 20.1.1.254
    domainsearch: tennet.local
    cpu: 4
    mem: 16GiB
vms_2nics:
  oshift-fc-nlb1.tennet.local:
    ip: 10.0.0.143
    mask: 255.255.0.0
    gateway: 10.0.1.1
    nameserver: 10.0.1.254 20.1.1.254
    domainsearch: tennet.local twentynet.local
    cpu: 2
    mem: 8GiB
    ip2: 20.0.0.131
    mask2: 255.255.0.0
    gateway2: 20.1.1.1
  oshift-fc-nlb2.tennet.local:
    ip: 10.0.0.144
    mask: 255.255.0.0
    gateway: 10.0.1.1
    nameserver: 10.0.1.254 20.1.1.254
    domainsearch: tennet.local twentynet.local
    cpu: 2
    mem: 8GiB
    ip2: 20.0.0.132
    mask2: 255.255.0.0
    gateway2: 20.1.1.1
