###
## Copyright (2018) Hewlett Packard Enterprise Development LP
##
## Licensed under the Apache License, Version 2.0 (the "License");
## You may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
####


---
# vars file for deploy-vm
engine_cafile: '/etc/pki/ovirt-engine/ca.pem'
datacenter: Default
cluster: Default
network: 'ovirtmgmt'
vmtemplate: rhel7-template_7.5_2d-50G
mgmt_gateway: 10.0.1.1
mgmt_mask: 255.255.0.0
mgmt_dns: 10.0.1.254
#private_hosted_zone: tennet.local

public_hosted_zone: tennet.local
#pub_mask: 255.0.0.0
#pub_gateway: 20.1.1.1
#pub_dns: 20.1.1.254

fqdnmaster1: oshift-fc-m1.tennet.local
fqdnmaster2: oshift-fc-m2.tennet.local
fqdnmaster3: oshift-fc-m3.tennet.local
fqdnetcd1: oshift-fc-etcd1.tennet.local
fqdnetcd2: oshift-fc-etcd2.tennet.local
fqdnetcd3: oshift-fc-etcd3.tennet.local
fqdninfra1: oshift-fc-infra1.tennet.local
fqdninfra2: oshift-fc-infra2.tennet.local
fqdninfra3: oshift-fc-infra3.tennet.local
fqdnlb1: oshift-fc-nlb1.tennet.local
fqdnlb2: oshift-fc-nlb2.tennet.local

#fqdn of RHVH cluster where the VMs are getting deployed
fqdnrhv1: 3rhvh01.tennet.local
fqdnrhv2: 3rhvh02.tennet.local
fqdnrhv3: 3rhvh03.tennet.local

storage_mask: 255.255.0.0

master01_ip: 10.0.8.134
master02_ip: 10.0.8.135
master03_ip: 10.0.8.136

lb01_ip: 10.0.8.143
lb02_ip: 10.0.8.144

infra01_ip: 10.0.8.140
infra02_ip: 10.0.8.141
infra03_ip: 10.0.8.142

etcd01_ip : 10.0.8.145
etcd02_ip : 10.0.8.146
etcd03_ip : 10.0.8.147

vms:
  oshift-fc-etcd1.tennet.local:
    ip: "{{etcd01_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
    domainsearch: "{{public_hosted_zone}}"
#    domainsearch: "{{private_hosted_zone}}"
    cpu: 4
    mem: 16GiB

  oshift-fc-etcd2.tennet.local:
    ip: "{{etcd02_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
    domainsearch: "{{public_hosted_zone}}"
#    domainsearch: "{{private_hosted_zone}}"
    cpu: 4
    mem: 16GiB

  oshift-fc-etcd3.tennet.local:
    ip: "{{etcd03_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
    domainsearch: "{{public_hosted_zone}}"
#    domainsearch: "{{private_hosted_zone}}"
    cpu: 4
    mem: 16GiB

#vms_2nics:

  oshift-fc-nlb1.tennet.local:
    ip: "{{lb01_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
    domainsearch: "{{public_hosted_zone}}"
#    domainsearch: "{{private_hosted_zone}}"
    cpu: 2
    mem: 8GiB

  oshift-fc-nlb2.tennet.local:
    ip: "{{lb02_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
    domainsearch: "{{public_hosted_zone}}"
#    domainsearch: "{{private_hosted_zone}}"
    cpu: 2
    mem: 8GiB


  oshift-fc-infra1.tennet.local:
    ip: "{{infra01_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
#    domainsearch: "{{private_hosted_zone}}"
    domainsearch: "{{public_hosted_zone}}"
    cpu: 4
    mem: 16GiB

  oshift-fc-infra2.tennet.local:
    ip: "{{infra02_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
#    domainsearch: "{{private_hosted_zone}}"
    domainsearch: "{{public_hosted_zone}}"
    cpu: 4
    mem: 16GiB

  oshift-fc-infra3.tennet.local:
    ip: "{{infra03_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
#    domainsearch: "{{private_hosted_zone}}"
    domainsearch: "{{public_hosted_zone}}"
    cpu: 4
    mem: 16GiB

  oshift-fc-m1.tennet.local:
    ip: "{{master01_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
#    domainsearch: "{{private_hosted_zone}}"
    domainsearch: "{{public_hosted_zone}}"
    cpu: 4
    mem: 16GiB

  oshift-fc-m2.tennet.local:
    ip: "{{master02_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
#    domainsearch: "{{private_hosted_zone}}"
    domainsearch: "{{public_hosted_zone}}"
    cpu: 4
    mem: 16GiB

  oshift-fc-m3.tennet.local:
    ip: "{{master03_ip}}"
    mask: "{{mgmt_mask}}"
    gateway: "{{mgmt_gateway}}"
    nameserver: "{{mgmt_dns}}"
#    domainsearch: "{{private_hosted_zone}}"
    domainsearch: "{{public_hosted_zone}}"
    cpu: 4
    mem: 16GiB


