---
  - name: Read password from file
    set_fact:
      password: "{{ lookup('file', password_file_path) }}"

  - name: Login to Mirror resitry with credentials
    shell: podman login {{ mirror_registry_fqdn }}:8443 -u init -p {{ password }}
    register: login

  - name: disply the login status
    debug:
      msg: "{{ login.stdout }}"

  - name: Login to Mirror resitry with auth file
    shell: podman login {{ mirror_registry_fqdn }}:8443 --authfile {{ LOCAL_SECRET_JSON }}
    register: authlogin

  - name: disply the auth login status
    debug:
      msg: "{{ authlogin.stdout }}"

  - name: Run OpenShift adm release mirror command
    shell: |
        oc adm release mirror -a {{ LOCAL_SECRET_JSON }} \
        --from=quay.io/{{ PRODUCT_REPO }}/{{ RELEASE_NAME }}:{{ OCP_RELEASE }}-{{ ARCHITECTURE }} \
        --to={{ LOCAL_REGISTRY }}/{{ LOCAL_REPOSITORY }} \
        --to-release-image={{ LOCAL_REGISTRY }}/{{ LOCAL_REPOSITORY }}:{{ OCP_RELEASE }}-{{ ARCHITECTURE }}
    register: mirror_output

  - name: Display mirror command output
    debug:
      msg: "{{ mirror_output.stdout }}"        
